set(SOURCES
    src/app/application.cc
    src/app/application.h
    src/app/ini.cc
    src/app/ini.h
    src/app/input.cc
    src/app/input.h
    src/app/main_thread.cc
    src/app/main_thread.h
    src/app/parameters.cc
    src/app/parameters.h
    src/app/task_system.cc
    src/app/task_system.h

    src/assets/animation.cc
    src/assets/animation.h
    src/assets/assets.cc
    src/assets/assets.h
    src/assets/assimp_blender.h
    src/assets/env_texture_manager.cc
    src/assets/env_texture_manager.h
    src/assets/mesh.cc
    src/assets/mesh.h
    src/assets/model.cc
    src/assets/model.h
    src/assets/model_manager.cc
    src/assets/model_manager.h
    src/assets/particle_manager.cc
    src/assets/particle_manager.h
    src/assets/stb_image.cc
    src/assets/texture_manager.cc
    src/assets/texture_manager.h
    src/assets/texture.cc
    src/assets/texture.h

    src/math/assimp_to_glm.h
    src/math/collision_types.cc
    src/math/collision_types.h
    src/math/fast_math.cc
    src/math/fast_math.h
    src/math/intersection.cc
    src/math/intersection.h
    src/math/random.cc
    src/math/random.h
    src/math/transformation.cc
    src/math/transformation.h

    src/opengl/buffer_storage.h
    src/opengl/buffer_storage.inl
    src/opengl/fence_sync.cc
    src/opengl/fence_sync.h
    src/opengl/framebuffer.cc
    src/opengl/framebuffer.h
    src/opengl/program.cc
    src/opengl/program.h
    src/opengl/query.cc
    src/opengl/query.h
    src/opengl/sampler.cc
    src/opengl/sampler.h
    src/opengl/shader.cc
    src/opengl/shader.h
    src/opengl/texture.cc
    src/opengl/texture.h
    src/opengl/uniform_buffer.cc
    src/opengl/uniform_buffer.h
    src/opengl/vertex_array.cc
    src/opengl/vertex_array.h
    src/opengl/vertex_buffers.cc
    src/opengl/vertex_buffers.h

    src/render/crosshair.cc
    src/render/crosshair.h
    src/render/framebuffers.cc
    src/render/framebuffers.h
    src/render/generated_mesh.cc
    src/render/generated_mesh.h
    src/render/generated_texture.cc
    src/render/generated_texture.h
    src/render/poisson.h
    src/render/programs.h
    src/render/renderer.cc
    src/render/renderer.h
    src/render/uniform_buffers.cc
    src/render/uniform_buffers.h
    src/render/vertex_arrays.cc
    src/render/vertex_arrays.h

    src/scene/camera_system.cc
    src/scene/camera_system.h
    src/scene/light_system.cc
    src/scene/light_system.h
    src/scene/object_system.cc
    src/scene/object_system.h
    src/scene/particle_system.cc
    src/scene/particle_system.h
    src/scene/props.cc
    src/scene/props.h
    src/scene/scene.cc
    src/scene/scene.h

    src/ui/imgui_toggle/imgui_toggle.cc
    src/ui/imgui_toggle/imgui_toggle.h
    src/ui/imguizmo.quat/imGuIZMOquat.cc
    src/ui/imguizmo.quat/imGuIZMOquat.h
    src/ui/imguizmo.quat/vgConfig.h
    src/ui/imguizmo.quat/vGizmo.h
    src/ui/imguizmo.quat/vgMath.h
    src/ui/base_components.h
    src/ui/base_types.h
    src/ui/loading_indicator.cc
    src/ui/loading_indicator.h
    src/ui/utility.cc
    src/ui/utility.h
    src/ui/win_scene.cc
    src/ui/win_scene.h
    src/ui/win_guizmo.cc
    src/ui/win_guizmo.h
    src/ui/win_layout.cc
    src/ui/win_layout.h
    src/ui/win_resources.cc
    src/ui/win_resources.h
    src/ui/win_settings.cc
    src/ui/win_settings.h

    src/utils/enums.h
    src/utils/output.cc
    src/utils/output.h
    src/utils/profiling.h
    src/utils/string_parsing.cc
    src/utils/string_parsing.h

    src/engine.cc
    src/engine.h
    src/events.cc
    src/events.h
    src/files.cc
    src/files.h
    src/global.h
    src/glsl_header.cc
    src/glsl_header.h
    src/id_generator.cc
    src/id_generator.h
    src/main.cc
    src/mem_info.cc
    src/mem_info.h
    src/mi_types.h
    src/options.cc
    src/options.h
)